from fpdf import FPDF
import random
import os

class PDF(FPDF):
    def __init__(self, orientation='P', unit='mm', format='A4'):
        super().__init__(orientation, unit, format)
        self.header_title = 'CBSE BOARD EXAMINATION'
        self.header_subtitle = 'Mock Question Paper - Generated by Learnixis'

    def header(self):
        # Logo or School Name
        self.set_font('Arial', 'B', 16)
        
        self.cell(0, 10, self.header_title, 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, self.header_subtitle, 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pyq_pdf(subject, class_num, year, dataset_code="SET-1"):
    pdf = PDF()
    pdf.add_page()
    
    # Metadata
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Subject: {subject}", 0, 1)
    pdf.cell(0, 10, f"Class: {class_num} | Year: {year} | Code: {dataset_code}", 0, 1)
    pdf.cell(0, 10, "Time: 3 Hours | Max Marks: 70/80", 0, 1)
    pdf.ln(5)
    
    # General Instructions
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 10, "General Instructions:", 0, 1)
    pdf.set_font("Arial", "", 9)
    instructions = [
        "1. This question paper contains 34 questions. All questions are compulsory.",
        "2. This question paper is divided into five sections: A, B, C, D and E.",
        "3. Section A contains 16 MCQs of 1 mark each.",
        "4. Section B contains 5 short answer type questions of 2 marks each.",
        "5. Section C contains 7 short answer type questions of 3 marks each.",
        "6. Section D contains 2 case based questions of 4 marks each.",
        "7. Section E contains 3 long answer type questions of 5 marks each."
    ]
    for inst in instructions:
        pdf.cell(0, 5, inst, 0, 1)
    pdf.ln(10)
    
    # Mock Questions
    sections = [
        ("Section A", "Multiple Choice Questions (1 Mark)", 5),
        ("Section B", "Short Answer Type I (2 Marks)", 3),
        ("Section C", "Short Answer Type II (3 Marks)", 3),
        ("Section D", "Long Answer Type (5 Marks)", 2)
    ]
    
    question_bank = {
        "Physics": [
            "Define Electric Flux. Write its SI unit.",
            "State properties of equipotential surfaces.",
            "Why do magnetic field lines form closed loops?",
            "Derive expression for torque on a dipole.",
            "Explain the principle of a transformer.",
            "What is the phenomenon of total internal reflection?",
            "Define threshold frequency in photoelectric effect.",
            "State Bohr's postulates for hydrogen atom."
        ],
        "Chemistry": [
            "Define Molality.",
            "State Henry's Law.",
            "Explain the structure of XeF4.",
            "Differentiate between Order and Molecularity of a reaction.",
            "Write the IUPAC name of the given compound.",
            "Explain Lanthanoid Contraction.",
            "What are transition elements?",
            "Explain SN1 and SN2 reaction mechanisms."
        ],
        "Biology": [
            "Draw a labeled diagram of a typical anatropous ovule.",
            "Explain the process of double fertilization.",
            "What is Spermatogenesis?",
            "Describe the structure of DNA.",
            "Explain the central dogma of molecular biology.",
            "What is Bt Cotton?",
            "Discuss the causes of biodiversity loss."
        ],
        "Mathematics": [
            "Find the inverse of the matrix.",
            "Solve the differential equation.",
            "Find the probability distribution of X.",
            "Integrate the functions.",
            "Find the shortest distance between lines.",
            "Maximize Z = 3x + 4y subject to constraints.",
            "Proof that the relation R is an equivalence relation."
        ],
        "Science 1": [
            "State Newton's Law of Gravitation.",
            "Explain Fleming's Left Hand Rule.",
            "Write the electron configuration of Carbon.",
            "What is corrosion? How can it be prevented?",
            "Explain the working of an electric motor.",
            "Define escape velocity and derive its formula."
        ],
        "Science 2": [
            "Draw a labeled diagram of the human respiratory system.",
            "Explain the process of mitosis.",
            "What is the importance of biodiversity conservation?",
            "Explain Darwin's theory of natural selection.",
            "What are vestigial organs? Give examples."
        ],
        "Math 1 (Algebra)": [
            "Solve by Cramer's Rule: 3x - 4y = 10; 4x + 3y = 5.",
            "Determine nature of roots for x^2 + 2x - 9 = 0.",
            "Find the 19th term of the AP: 7, 13, 19, 25...",
            "Two coins are tossed simultaneously. Find P(at least one head).",
            "Draw the frequency polygon for the given data."
        ],
        "Math 2 (Geometry)": [
            "State and prove Basic Proportionality Theorem (BPT).",
            "Find coordinates of midpoint of segment joining (-4, 2) and (6, 2).",
            "Find the volume of a sphere with radius 7cm.",
            "Prove that opposite angles of a cyclic quadrilateral are supplementary.",
            "Construct a tangent to a circle from a point outside it."
        ]
    }
    
    # Fallback for unknown subjects
    if subject not in question_bank:
        questions = question_bank["Physics"] # Default fallback
    else:
        questions = question_bank[subject]
    
    total_q = 1
    for sec_name, desc, count in sections:
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, f"{sec_name}: {desc}", 0, 1)
        pdf.set_font("Arial", "", 10)
        
        for _ in range(count):
            q_text = random.choice(questions)
            pdf.multi_cell(0, 7, f"Q{total_q}. {q_text}")
            total_q += 1
        pdf.ln(5)
        
    # Ensure directory exists
    output_dir = "downloads"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    filename = f"{output_dir}/CBSE_{class_num}_{subject}_{year}_{dataset_code}.pdf"
    pdf.output(filename)
    return filename

def generate_qa_pdf(chapter_name, questions):
    """Generates a PDF for the Q&A List."""
    pdf = PDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"Important Questions: {chapter_name}", 0, 1, 'C')
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Curated by Learnixis AI", 0, 1, 'C')
    pdf.ln(5)
    
    for q in questions:
        # Question
        pdf.set_font("Arial", "B", 11)
        pdf.multi_cell(0, 7, f"Q{q['id']}. {q['question']} ({q['difficulty']})")
        
        # Answer
        pdf.set_font("Arial", "", 10)
        # Handle unicode roughly (replace common issues)
        clean_answer = q['answer'].encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, f"Ans: {clean_answer}")
        pdf.ln(3)

    # Ensure directory exists
    output_dir = "downloads"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    safe_name = "".join([c for c in chapter_name if c.isalnum() or c in (' ','-','_')]).strip()
    filename = f"{output_dir}/QA_{safe_name}.pdf"
    pdf.output(filename)
    return filename

def sanitize(text, is_marathi=False):
    """Replaces common non-latin-1 characters to prevent PDF generation errors."""
    # If standard sanitize used for Marathi without font, it wipes everything.
    # If font is present, we don't need to strip as aggressively, but FPDF still needs Unicode.
    if is_marathi:
        return text # Trust the font handle to handle it, or it will crash.
        
    replacements = {
        '\u2018': "'", '\u2019': "'",  # Smart quotes
        '\u201c': '"', '\u201d': '"',  # Smart double quotes
        '\u2013': '-', '\u2014': '-',  # Dashes
        '\u2026': '...',               # Ellipsis
        '\u2212': '-',                 # Minus sign
    }
    # First do mapped replacements
    for char, rep in replacements.items():
        text = text.replace(char, rep)
    
    # Then force encode/decode to strip anything else
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_chapter_notes(chapter_name, subject, flashcards, medium="English"):
    """Generates an AI-written textbook chapter PDF with comprehensive details."""
    pdf = PDF()
    
    # Register Marathi Font if needed
    base_path = os.path.dirname(os.path.abspath(__file__))
    font_path = os.path.join(base_path, "NotoSansDevanagari-Regular.ttf")
    has_marathi_font = False
    
    if medium == "Marathi" and os.path.exists(font_path):
        try:
            pdf.add_font("Marathi", "", font_path)
            has_marathi_font = True
        except Exception as e:
            print(f"Font loading failed: {e}")
    
    pdf.add_page()
    
    # Select Font Family
    font_family = "Marathi" if (medium == "Marathi" and has_marathi_font) else "Arial"
    
    # Title Page
    pdf.set_font(font_family, "B", 24)
    # Sanitize only if NOT marathi or if font failed
    safe_chapter_name = chapter_name if has_marathi_font else sanitize(chapter_name)
    pdf.cell(0, 20, safe_chapter_name, 0, 1, 'C')
    
    pdf.set_font(font_family, "", 16)
    sub_text = f"Subject: {subject}" if medium == "English" else f"विषय: {subject}"
    pdf.cell(0, 10, sub_text if has_marathi_font else sanitize(sub_text), 0, 1, 'C')
    
    pdf.set_font(font_family, "I", 12)
    note_title = "Comprehensive Study Notes & Key Points" if medium == "English" else "सविस्तर अभ्यास नोट्स आणि महत्त्वाचे मुद्दे"
    pdf.cell(0, 10, note_title if has_marathi_font else sanitize(note_title), 0, 1, 'C')
    pdf.ln(10)
    
    # 1. Introduction
    pdf.set_font(font_family, "B", 14)
    intro_head = "1. Introduction" if medium == "English" else "१. प्रस्तावना"
    pdf.cell(0, 10, intro_head if has_marathi_font else sanitize(intro_head), 0, 1)
    
    pdf.set_font(font_family, "", 11)
    
    if medium == "Marathi":
        intro_text = f"या प्रकरणाचा मुख्य उद्देश म्हणजे {chapter_name} मधील मूलभूत संकल्पना स्पष्ट करणे. बोर्ड परीक्षेच्या दृष्टीने हा धडा अत्यंत महत्त्वाचा आहे. विद्यार्थ्यांनी या नोट्स काळजीपूर्वक वाचाव्यात."
    else:
        intro_map = {
            "Physics": "Physics is the study of matter and energy. This chapter explores fundamental principles governing natural phenomena. We will delve into mathematical derivations and physical interpretations of these concepts.",
            "Chemistry": "Chemistry bridges physics and biology. In this chapter, we examine the composition, structure, and changes of matter. Understanding these reactions is key to mastering the subject.",
            "Biology": "Biology is the science of life. This chapter focuses on the detailed mechanisms of living organisms, from cellular processes to ecosystem dynamics.",
            "Mathematics": "Mathematics is the language of the universe. This chapter introduces critical analytical tools and problem-solving techniques essential for higher-level calculus and algebra."
        }
        intro_base = intro_map.get(subject, "This chapter explains core concepts and their applications in the real world.")
        intro_text = f"{intro_base} The topic of '{chapter_name}' is particularly significant for the Board Examinations. It lays the groundwork for understanding more complex systems and is frequently tested in both objective and subjective sections. Students are advised to pay close attention to the definitions and standard diagrams presented herein."
    
    pdf.multi_cell(0, 7, intro_text if has_marathi_font else sanitize(intro_text))
    pdf.ln(5)
    
    # 2. Detailed Theoretical Analysis
    pdf.set_font(font_family, "B", 14)
    theory_head = "2. Detailed Theoretical Analysis" if medium == "English" else "२. सविस्तर तात्विक विश्लेषण"
    pdf.cell(0, 10, theory_head if has_marathi_font else sanitize(theory_head), 0, 1)
    pdf.set_font(font_family, "", 11)
    
    if medium == "Marathi":
        theory_text = f"""
        २.१ मूलभूत तत्त्वे
        {chapter_name} या पाठाचा गाभा म्हणजे त्यातील वैज्ञानिक तत्त्वे. संकल्पना समजून घेण्यासाठी त्यांची पडताळणी करणे आवश्यक आहे.

        २.२ कार्यपद्धती आणि प्रक्रिया
        या प्रकरणातील बहुतेक घटना पायरी-पायरीने स्पष्ट केल्या जाऊ शकतात.
        - प्रथम, प्रणाली किंवा घटक ओळखा.
        - दुसरे, संबंधित नियम लागू करा.
        - तिसरे, अंतिम निष्पत्ती तपासा.
        """
    else:
        theory_text = f"""
        2.1 Fundamental Principles
        The core of {chapter_name} lies in its defining principles. Whether it involves conservation laws in Physics, reaction mechanisms in Chemistry, or physiological processes in Biology, the underlying logic remains consistent. Detailed observation and verification are required to master these topics.

        2.2 Mechanism and Process
        Most phenomena in this chapter can be described by a step-by-step process. 
        - First, identify the system or entity clearly.
        - Second, apply the relevant laws (e.g., Newton's Laws, Thermodynamic Laws, or Biological Dogmas).
        - Third, solve for the unknown or describe the resulting state.
        
        2.3 Critical Analysis
        When analyzing problems related to {chapter_name}, it is crucial to consider the boundary conditions and assumptions. For instance, is the system isolated? is the reaction reversible? or is the genetic trait dominant? These nuances often determine the final outcome of the analysis.
        """
    pdf.multi_cell(0, 7, theory_text if has_marathi_font else sanitize(theory_text))
    pdf.ln(5)

    # 3. Key Concepts & Definitions
    pdf.set_font(font_family, "B", 14)
    concepts_head = "3. Core Concepts & Definitions" if medium == "English" else "३. मुख्य संकल्पना आणि व्याख्या"
    pdf.cell(0, 10, concepts_head if has_marathi_font else sanitize(concepts_head), 0, 1)
    
    if flashcards:
        for card in flashcards:
            term = card.get('term', 'Term')
            definition = card.get('definition', 'Definition')
            
            pdf.set_font(font_family, "B", 11)
            pdf.cell(0, 7, f"• {term}:" if has_marathi_font else sanitize(f"• {term}:"), 0, 1)
            pdf.set_font(font_family, "", 11)
            pdf.multi_cell(0, 7, f"  {definition}" if has_marathi_font else sanitize(f"  {definition}"))
            pdf.ln(2)
    else:
        pdf.set_font(font_family, "", 11)
        no_fc_text = "Key concepts typically include Laws and definitions." if medium == "English" else "मुख्य संकल्पनांमध्ये नियम आणि व्याख्यांचा समावेश होतो."
        pdf.multi_cell(0, 7, no_fc_text if has_marathi_font else sanitize(no_fc_text))
    
    pdf.ln(5)

    # 4. Key Points to Remember
    pdf.set_font(font_family, "B", 14)
    pdf.set_text_color(220, 50, 50) # Red-ish
    kp_head = "4. Key Points to Remember (Exam Focus)" if medium == "English" else "४. लक्षात ठेवण्यासारखे महत्त्वाचे मुद्दे (परीक्षा विशेष)"
    pdf.cell(0, 10, kp_head if has_marathi_font else sanitize(kp_head), 0, 1)
    pdf.set_text_color(0, 0, 0) # Reset
    
    pdf.set_font(font_family, "", 11)
    
    if medium == "Marathi":
        key_points = [
            "गणिते सोडवताना नेहमी आधी सूत्र/व्याख्या लिहा.",
            "SI एककांचे भान ठेवा.",
            "आकृत्यांसाठी पेन्सिलचा वापर करा आणि नावे स्पष्ट द्या.",
            f"{chapter_name} मधील आलेखांचे निरीक्षण काळजीपूर्वक करा.",
            "एमसीक्यू (MCQ) साठी 'अपवाद' नियम लक्षात ठेवा.",
        ]
    else:
        key_points = [
            "Always write the standard formula/definition first before solving numericals.",
            "Check units consistency (SI units) throughout the calculation.",
            "For diagrams, use a sharp pencil and label all parts clearly.",
            f"In {chapter_name}, derived graphs often carry marks for slope and intercept interpretation.",
            "Review the 'Exceptions' to general rules, as these are often asked in MCQs.",
            "Practice the specific derivations listed in the syllabus multiple times.",
            "Time Management: Do not spend more than 5 minutes on a 2-mark question."
        ]
    
    for i, kp in enumerate(key_points, 1):
        pdf.multi_cell(0, 7, f"{i}. {kp}" if has_marathi_font else sanitize(f"{i}. {kp}"))
    
    pdf.ln(5)
    
    # 5. Summary
    pdf.set_font(font_family, "B", 14)
    sum_head = "5. Chapter Summary" if medium == "English" else "५. सारांश"
    pdf.cell(0, 10, sum_head if has_marathi_font else sanitize(sum_head), 0, 1)
    pdf.set_font(font_family, "", 11)
    
    sum_text = "In conclusion, regular revision is key." if medium == "English" else "सारांश: नियमित उजळणीमुळेच यश मिळेल. वरील व्याख्या आणि तत्त्वे बोर्ड परीक्षेत चांगली गुण मिळवण्यासाठी अत्यावश्यक आहेत."
    pdf.multi_cell(0, 7, sum_text if has_marathi_font else sanitize(sum_text))
    
    # Save
    output_dir = "books"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    safe_name = "".join([c for c in chapter_name if c.isalnum() or c in (' ','-','_')]).strip()
    filename = f"{output_dir}/{safe_name}_AI_Notes.pdf"
    pdf.output(filename)
    return filename

def generate_markdown_to_pdf(markdown_content, filename_base, is_marathi=False):
    """Converts a partial Markdown string (Question Bank) to PDF."""
    pdf = PDF()
    pdf.header_title = "MAHARASHTRA STATE BOARD"
    pdf.header_subtitle = "Question Bank (2025) - Generated by Learnixis"
    
    base_path = os.path.dirname(os.path.abspath(__file__))
    font_path = os.path.join(base_path, "NotoSansDevanagari-Regular.ttf")
    has_marathi_font = False
    
    latin_path = os.path.join(base_path, "NotoSans-Regular.ttf")
    
    # Logging to debug
    with open("pdf_debug.log", "a") as log:
        log.write(f"\\n--- New Generation ---\\n")
        log.write(f"Subject: {filename_base} | is_marathi: {is_marathi}\\n")
        log.write(f"Base Path: {base_path}\\n")
        log.write(f"Font Path: {font_path} | Exists: {os.path.exists(font_path)}\\n")

    if is_marathi and os.path.exists(font_path):
        try:
            # Register Marathi for all styles
            pdf.add_font("Marathi", "", font_path)
            pdf.add_font("Marathi", "B", font_path)
            pdf.add_font("Marathi", "I", font_path)
            pdf.add_font("Marathi", "BI", font_path)
            has_marathi_font = True
            
            with open("pdf_debug.log", "a") as log:
                log.write("Marathi Font Registered Successfully.\\n")
                
            # Use Latin fallback if available
            if os.path.exists(latin_path):
                pdf.add_font("Latin", "", latin_path)
                pdf.add_font("Latin", "B", latin_path) 
                pdf.set_fallback_fonts(["Latin"])
                
        except Exception as e:
            with open("pdf_debug.log", "a") as log:
                log.write(f"Font loading failed: {str(e)}\\n")
            print(f"Font loading failed: {e}")
    else:
        with open("pdf_debug.log", "a") as log:
            log.write("Skipping Marathi Font registration (Condition Failed).\\n")
            
    pdf.add_page()
    
    # Select Font Family
    font_family = "Marathi" if (is_marathi and has_marathi_font) else "Arial"
    
    lines = markdown_content.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(2)
            continue
            
        # Clean text specifically for FPDF2 issues
        # Replace escaped underscores
        line = line.replace("\\_", "_")
        # Replace long sequences of underscores with a shorter version to prevent wrapping issues
        while "______" in line:
            line = line.replace("______", "___")
            
        while "______" in line:
            line = line.replace("______", "___")
        
        try:
            # Headers
            if line.startswith('# '):
                pdf.set_font(font_family, "B", 18)
                text = line.replace('# ', '')
                pdf.multi_cell(0, 10, text if has_marathi_font else sanitize(text), 0, 'C')
                pdf.ln(5)
            elif line.startswith('## '):
                pdf.set_font(font_family, "B", 14)
                text = line.replace('## ', '')
                pdf.cell(0, 10, text if has_marathi_font else sanitize(text), 0, 1)
            elif line.startswith('### '):
                pdf.set_font(font_family, "B", 12)
                text = line.replace('### ', '')
                pdf.cell(0, 8, text if has_marathi_font else sanitize(text), 0, 1)
            # List Items
            elif line.startswith('- ') or line.startswith('* '):
                pdf.set_font(font_family, "", 10)
                text = line[2:] # Strip '- '
                # crude bold handling for **text**
                if "**" in text:
                    text = text.replace("**", "") # Remove markers for simplicity in PDF
                    
                pdf.multi_cell(0, 6, f"• {text}" if has_marathi_font else sanitize(f"• {text}"))
            # Numbered List (Simple detection)
            elif line[0].isdigit() and ". " in line[:4]:
                 pdf.set_font(font_family, "", 10)
                 # crude bold handling
                 if "**" in line:
                     line = line.replace("**", "")
                 pdf.multi_cell(0, 6, line if has_marathi_font else sanitize(line))
            # Tables (Very crude fallback)
            elif "|" in line:
                 pdf.set_font(font_family, "I", 8)
                 pdf.cell(0, 5, line if has_marathi_font else sanitize(line), 0, 1)
            # Normal Text
            else:
                pdf.set_font(font_family, "", 10)
                if "**" in line:
                    line = line.replace("**", "")
                pdf.multi_cell(0, 6, line if has_marathi_font else sanitize(line))
        except Exception as e:
            print(f"Error rendering line: {str(e)}")
            # Fallback: Try writing it as simple ASCII if possible, or just skip
            pdf.set_font("Arial", "I", 8)
            pdf.cell(0, 5, "[Error rendering content: Format issue]", 0, 1)
            
    # Save
    output_dir = "downloads"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    filename = f"{output_dir}/{filename_base.replace('.md', '.pdf')}"
    pdf.output(filename)
    return filename
