from fpdf import FPDF
import random
import os

class PDF(FPDF):
    def header(self):
        # Logo or School Name
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'CBSE BOARD EXAMINATION', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Mock Question Paper - Generated by Learnixis', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pyq_pdf(subject, class_num, year, dataset_code="SET-1"):
    pdf = PDF()
    pdf.add_page()
    
    # Metadata
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Subject: {subject}", 0, 1)
    pdf.cell(0, 10, f"Class: {class_num} | Year: {year} | Code: {dataset_code}", 0, 1)
    pdf.cell(0, 10, "Time: 3 Hours | Max Marks: 70/80", 0, 1)
    pdf.ln(5)
    
    # General Instructions
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 10, "General Instructions:", 0, 1)
    pdf.set_font("Arial", "", 9)
    instructions = [
        "1. This question paper contains 34 questions. All questions are compulsory.",
        "2. This question paper is divided into five sections: A, B, C, D and E.",
        "3. Section A contains 16 MCQs of 1 mark each.",
        "4. Section B contains 5 short answer type questions of 2 marks each.",
        "5. Section C contains 7 short answer type questions of 3 marks each.",
        "6. Section D contains 2 case based questions of 4 marks each.",
        "7. Section E contains 3 long answer type questions of 5 marks each."
    ]
    for inst in instructions:
        pdf.cell(0, 5, inst, 0, 1)
    pdf.ln(10)
    
    # Mock Questions
    sections = [
        ("Section A", "Multiple Choice Questions (1 Mark)", 5),
        ("Section B", "Short Answer Type I (2 Marks)", 3),
        ("Section C", "Short Answer Type II (3 Marks)", 3),
        ("Section D", "Long Answer Type (5 Marks)", 2)
    ]
    
    question_bank = {
        "Physics": [
            "Define Electric Flux. Write its SI unit.",
            "State properties of equipotential surfaces.",
            "Why do magnetic field lines form closed loops?",
            "Derive expression for torque on a dipole.",
            "Explain the principle of a transformer.",
            "What is the phenomenon of total internal reflection?",
            "Define threshold frequency in photoelectric effect.",
            "State Bohr's postulates for hydrogen atom."
        ],
        "Chemistry": [
            "Define Molality.",
            "State Henry's Law.",
            "Explain the structure of XeF4.",
            "Differentiate between Order and Molecularity of a reaction.",
            "Write the IUPAC name of the given compound.",
            "Explain Lanthanoid Contraction.",
            "What are transition elements?",
            "Explain SN1 and SN2 reaction mechanisms."
        ],
        "Biology": [
            "Draw a labeled diagram of a typical anatropous ovule.",
            "Explain the process of double fertilization.",
            "What is Spermatogenesis?",
            "Describe the structure of DNA.",
            "Explain the central dogma of molecular biology.",
            "What is Bt Cotton?",
            "Discuss the causes of biodiversity loss."
        ],
        "Mathematics": [
            "Find the inverse of the matrix.",
            "Solve the differential equation.",
            "Find the probability distribution of X.",
            "Integrate the functions.",
            "Find the shortest distance between lines.",
            "Maximize Z = 3x + 4y subject to constraints.",
            "Proof that the relation R is an equivalence relation."
        ]
    }
    
    questions = question_bank.get(subject, question_bank["Physics"])
    
    total_q = 1
    for sec_name, desc, count in sections:
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, f"{sec_name}: {desc}", 0, 1)
        pdf.set_font("Arial", "", 10)
        
        for _ in range(count):
            q_text = random.choice(questions)
            pdf.multi_cell(0, 7, f"Q{total_q}. {q_text}")
            total_q += 1
        pdf.ln(5)
        
    # Ensure directory exists
    output_dir = "downloads"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    filename = f"{output_dir}/CBSE_{class_num}_{subject}_{year}_{dataset_code}.pdf"
    pdf.output(filename)
    return filename

def generate_qa_pdf(chapter_name, questions):
    """Generates a PDF for the Q&A List."""
    pdf = PDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"Important Questions: {chapter_name}", 0, 1, 'C')
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Curated by Learnixis AI", 0, 1, 'C')
    pdf.ln(5)
    
    for q in questions:
        # Question
        pdf.set_font("Arial", "B", 11)
        pdf.multi_cell(0, 7, f"Q{q['id']}. {q['question']} ({q['difficulty']})")
        
        # Answer
        pdf.set_font("Arial", "", 10)
        # Handle unicode roughly (replace common issues)
        clean_answer = q['answer'].encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, f"Ans: {clean_answer}")
        pdf.ln(3)

    # Ensure directory exists
    output_dir = "downloads"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    safe_name = "".join([c for c in chapter_name if c.isalnum() or c in (' ','-','_')]).strip()
    filename = f"{output_dir}/QA_{safe_name}.pdf"
    pdf.output(filename)
    return filename
